#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

- name:  Hosts addresses
  hosts: all
  become: false
  tasks:
    - debug:
        msg: "RocketMQ broker servers {{ item }}"
      with_items: "{{ groups['rmq-broker'] }}"
    - debug:
        msg: "RocketMQ name servers {{ item }}"
      with_items: "{{ groups['rmq-namesrv'] }}"
    - debug:
        msg: "RocketMQ console servers {{ item }}"
      with_items: "{{ groups['rmq-console'] }}"
    - debug:
        msg: "env is {{ env }}"

- name: RocketMQ setup
  hosts: all
  connection: ssh
  become: true
  tasks:
    - name: Install RPM packages
      yum: pkg={{ item }} state=latest
      with_items:
          - wget
          - sysstat
          - unzip
          - git
          - java-1.8.0-openjdk-devel.x86_64

    - name: Download Apache Maven
      unarchive:
        src: http://apache.claz.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
        remote_src: yes
        dest: /opt/

    - file: path=/opt/rocketmq state=directory
    - set_fact:
        nameServers: "{{ groups['rmq-namesrv']|map('extract', hostvars, ['ansible_default_ipv4', 'address'])|map('regex_replace', '(.*)', '\\1:9876') | join(';') }}"
        rocketMQVersion: "4.7.1"

    - name: Download RocketMQ package
      unarchive:
        src: https://downloads.apache.org/rocketmq/{{ rocketMQVersion }}/rocketmq-all-{{ rocketMQVersion }}-bin-release.zip
        remote_src: yes
        dest: /opt/rocketmq
  
    - set_fact:
        privateIp: "{{ hostvars[inventory_hostname]['ansible_facts']['eth0']['ipv4']['address'] }}"

    - name: Change locale to en_US.utf-8
      shell: |
        echo 'LANG=en_US.utf-8
              LC_ALL=en_US.utf-8' > /etc/environment

- name: Setup RocketMQ Broker
  hosts: rmq-broker
  connection: ssh
  become: true
  tasks:
    - set_fact:
        brokerName: "{{ groups['rmq-broker'].index(inventory_hostname) }}"
    - name: Set up broker
      template:
        src: "templates/rmq-broker.properties"
        dest: "/opt/rocketmq/rocketmq-all-4.7.1-bin-release/conf/rmq-broker.properties"
    - template:
        src: "templates/rmq-broker.service"
        dest: "/etc/systemd/system/rmq-broker.service"
    - name: Copy runserver.sh
      template:
        src: "templates/runserver.sh"
        dest: "/opt/rocketmq/rocketmq-all-4.7.1-bin-release/bin/runserver.sh"
      when: env == "dev"
    - name: Copy runbroker.sh
      template:
        src: "templates/runbroker.sh"
        dest: "/opt/rocketmq/rocketmq-all-4.7.1-bin-release/bin/runbroker.sh"
      when: env == "dev"        
    - systemd:
        state: restarted
        daemon_reload: yes
        name: "rmq-broker"

- name: Setup RocketMQ NameServer
  hosts: rmq-namesrv
  connection: ssh
  become: true
  tasks:
    - name: Set up RocketMQ NameServer
      template:
        src: "templates/rmq-namesrv.properties"
        dest: "/opt/rocketmq/rocketmq-all-4.7.1-bin-release/conf/rmq-namesrv.properties"
    - template:
        src: "templates/rmq-namesrv.service"
        dest: "/etc/systemd/system/rmq-namesrv.service"
    - name: Copy runserver.sh
      template:
        src: "templates/runserver.sh"
        dest: "/opt/rocketmq/rocketmq-all-4.7.1-bin-release/bin/runserver.sh"
      when: env == "dev"
    - name: Copy runbroker.sh
      template:
        src: "templates/runbroker.sh"
        dest: "/opt/rocketmq/rocketmq-all-4.7.1-bin-release/bin/runbroker.sh"
      when: env == "dev"        
    - systemd:
        state: restarted
        daemon_reload: yes
        name: "rmq-namesrv"

- name: Setup RocketMQ Console
  hosts: rmq-console
  connection: ssh
  become: true
  tasks:
    - name: Clean RocketMQ Console Artifact Path
      file:
        state: absent
        path: "/opt/rocketmq/rocketmq-externals"
    - name: Clone RocketMQ Console
      shell: git clone https://github.com/apache/rocketmq-externals.git
      args:
        chdir: /opt/rocketmq
    - name: Compile RocketMQ Console
      shell: /opt/apache-maven-3.6.3/bin/mvn clean package -Dmaven.test.skip=true
      args:
        chdir: /opt/rocketmq/rocketmq-externals/rocketmq-console
    - name: Run RocketMQ Console
      shell: java -jar target/rocketmq-console-ng*.jar
      args:
        chdir: /opt/rocketmq/rocketmq-externals/rocketmq-console